### PR TITLE
Missing header dependencies

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
On Mon, Dec 05, 2016 at 07:49:40AM -0800, Tancrède Lepoint wrote:
> Could you add travis integration to the project (so that PR are automatically checked)?

I'd love too, but that would mply travis acces to qb repos and we don't
want that. maybe move nfllib to another organisation?

**Comment by carlosaguilarmelchor** [comment]
Ok with me for merging the PR.
I agree about Travis, but we have to ask to Fred first. Then we can move it to the XPIR organization were the project started or to another organization if you prefer (e.g. a NFLlib organization).
Any suggestions ?
@serge-sans-paille @aguinet  if we move out of the quarkslab organization would it have consequences on your implication ?

**Comment by tlepoint** [comment]
OK to move it 👍

**Comment by cedricvanrompay** [comment]
Hi,

Still no merge?

**Comment by carlosaguilarmelchor** [comment]
Hi this was left hanging given the strategic issues discussed. I merge it right away.

**Pull request merged**
