### PR TITLE
Feature: constructor with iterator pair

### PR DESCRIPTION
**Pull request by tlepoint**
Add a constructor to poly() that takes as input a pair of iterators.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
LGTM, could you just add a test case?

**Comment by carlosaguilarmelchor** [comment]
Ok with me too. The unitary test would be indeed a good thing.

**Comment by tlepoint** [comment]
I added a test case. However, this showed some unspecified behavior:

- When we initialized the polynomials from less than "degree" elements, I think we should have taken each coefficient modulo the current modulus (in case it was not reduced), so I performed that change.
- When we initialize with "degree*nmoduli" elements, I think we can assume that everything is already reduced accordingly, so I didn't change the current code.

This might impact slightly the performances. Is that OK for you?

**Comment by carlosaguilarmelchor** [comment]
Hmm it is annoying specially when we just want to initialize a null or unit polynomial ...
Maybe you can add a boolean argument "reduce_coeffs" to the constructor with a default value of "true" ?
By default it will be correct but if you know the trick you can set it to false and have a faster init.

**Comment by tlepoint** [comment]
Ok, done. I added the tests on the test file to verify there is no reduction if the argument is set to false.
To be consistent, I also modified the behavior when we provide degree*nmoduli values.

**Comment by carlosaguilarmelchor** [comment]
Great the PR is ready for me. If no other requests are raised I will merge it tomorrow.

**Pull request merged**
