### PR TITLE
Feature/initial push

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Just a WIP, to check travis integration

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
@carlosaguilarmelchor , @tlepoint & @aguinet : the initial travis setup seems ok, it runs test with g++ and clang++, both in normal and optimized mode. there are a few test errors in optimized mode though :-/
I can't reproduce them on my laptop, and it's getting late...

**Comment by carlosaguilarmelchor** [comment]
@tlepoint @aguinet do not merge this PR until @serge-sans-paille finishes working on it !

**Comment by serge-sans-paille** [comment]
@carlosaguilarmelchor I added the doc you reviewed, if that's ok with you I'll make the initial release

**Comment by serge-sans-paille** [comment]
@carlosaguilarmelchor youhou?

**Comment by carlosaguilarmelchor** [comment]
I added a commit on the branch to complete the doc concerning the gaussian generator. 
@tlepoint shall we merge the branch now or you want to contribute to the doc before ?

**Comment by tlepoint** [comment]
@carlosaguilarmelchor I think we can merge it now.

**Comment by carlosaguilarmelchor** [comment]
Merging ...

**Pull request merged**
