### PR TITLE
Do not compile tests as part of make all

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Comment by tlepoint** [comment]
Works great for me, thanks. OK to merge.

**Comment by carlosaguilarmelchor** [comment]
`make` works for me but `make test` hangs.

Shouldn't the tests be compiled before being ran when doing `make test` ?

**Comment by serge-sans-paille** [comment]
On Wed, May 11, 2016 at 12:46:39AM -0700, Carlos Aguilar Melchor wrote:
> `make` works for me but `make test` hangs.

hangs? Compiling the tests is now part of the tests, a test like the
others...

**Comment by carlosaguilarmelchor** [comment]
```
Test project /home/carlos/sync/programmation/NFLlib/_build
      Start  1: build_nfllib_demo8192_124_uint64_t_op
 1/90 Test  #1: build_nfllib_demo8192_124_uint64_t_op .....   Passed  116.91 sec
```

Ok I supposed it did hang, but it was just terribly slow... 

May be a warning message could be displayed at the beginning of the tests ?

**Comment by tlepoint** [comment]
It takes 11 seconds on my computer, it surprises me it is so slow for you. Also maybe we could do the tests for increasing-size configurations?

**Comment by carlosaguilarmelchor** [comment]
It is strange I ran it on an high-end server with an Intel(R) Xeon(R) CPU E5-2695 v3 @ 2.30GHz and it took 45 secs to compile the first test. That is way too much.

Besides there seems to be a regression.

In master:
```
time (make && make test)
...
real	2m10.933s
user	2m2.458s
sys	0m8.104s
``` 

In feature/defered-tests-compilation:
```
time (make && make test)
...
real	5m24.094s
user	4m52.864s
sys	0m30.018s
```

**Comment by serge-sans-paille** [comment]
@carlosaguilarmelchor : we're still building the same binaries but without parallelism. I can't see another reason for the timing change.

I tested the manual build time with and without this commit, and it's comparable

**Comment by carlosaguilarmelchor** [comment]
How did you test the manual build time ?

**Comment by serge-sans-paille** [comment]
On Wed, May 11, 2016 at 08:22:51AM -0700, Carlos Aguilar Melchor wrote:
> How did you test the manual build time ? 

I retrived the command from the Testing/Temporary/LastTest.log file

**Comment by serge-sans-paille** [comment]
@carlosaguilarmelchor I leave it to you to accept this or not

**Comment by carlosaguilarmelchor** [comment]
@tlepoint can you test in AWS  the build times as I did ?

**Comment by tlepoint** [comment]
@carlosaguilarmelchor Just tested on an archlinux on AWS c4.xlarge, and the first test (compilation) takes 19s

`1/90 Test  #1: build_nfllib_demo8192_124_uint64_t_op .....   Passed   19.39 sec`

but it uses g++-6, maybe that speeds up things. Do you have an instance/os to reproduce the slow compilation?

**Comment by carlosaguilarmelchor** [comment]
Ubuntu g++-5.3

**Comment by tlepoint** [comment]
Just did on a newly created instance, installed g++-5, libgmp-dev, libmpfr-dev, cmake, git and `time (make && make test)` gives

master:
```
real	1m42.624s
user	1m36.036s
sys	0m6.573s
```

this branch:
```
real	1m43.037s
user	1m35.388s
sys	0m7.708s
```

**Comment by carlosaguilarmelchor** [comment]
Ok my bad ... my master branch did not point to the right repository ...

**Pull request merged**
